/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package minor_project;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.lang.reflect.Method;
import java.net.URL;
import java.net.URLClassLoader;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Random;
import java.util.Scanner;
import javax.swing.JFrame;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.tools.JavaCompiler;
import javax.tools.ToolProvider;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author saksham
 */
public class comp_alg extends javax.swing.JFrame {

    /**
     * Creates new form comp_alg
     */
    public comp_alg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        alg1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        alg2 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        alg1.setColumns(20);
        alg1.setRows(5);
        alg1.setText("ENTER FIRST ALGORITHM");
        jScrollPane2.setViewportView(alg1);

        alg2.setColumns(20);
        alg2.setRows(5);
        alg2.setText("ENTER SECOND ALGORITHM");
        jScrollPane1.setViewportView(alg2);

        jButton1.setText("GRAPH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("alg1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("alg2");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String query = "select * from temp1", query2 = "select * from temp2";
            Connection mycon = JDBC_connect.connect_it();
            Statement st = mycon.createStatement();
            XYSeriesCollection xysr = new XYSeriesCollection();
            XYSeries algo1 = new XYSeries("algo1");
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                algo1.add(rs.getInt("size"), rs.getInt("time"));
            }
            rs.close();
            XYSeries algo2 = new XYSeries("algo2");
            ResultSet rs1 = st.executeQuery(query2);
            while (rs1.next()) {
                algo2.add(rs1.getInt("size"), rs1.getInt("time"));
            }
            xysr.addSeries(algo1);
            xysr.addSeries(algo2);
            JFreeChart xychart = ChartFactory.createXYLineChart("SIZE-TIME CURVE", "INPUT SIZE", "TIME\nIN MICROSECONDS", xysr, PlotOrientation.VERTICAL, true, true, false);
            ChartPanel panel = new ChartPanel(xychart);
            JFrame frame = new JFrame("GRAPH");
            frame.add(panel);
            frame.setSize(500, 500);
            frame.setVisible(true);
            //panel.setPreferredSize(new java.awt.Dimension(560,367));
            //XYPlot plot = xychart.getXYPlot();
            panel.setVisible(true);
            frame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        } catch (Exception e) {
            System.out.println("aapse na ho paega");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  try {
            File f = new File("C:\\Users\\saksham\\desktop\\prog1.java");
            FileWriter fw = new FileWriter(f);
            PrintWriter pw = new PrintWriter(fw);
            String s;
            s = alg1.getText();
            System.out.println("String is: " + s);
            pw.print(s);
            fw.flush();

            fw.close();
        } catch (Exception e) {
        }   
    String filetocompile = "C:\\Users\\saksham\\desktop\\prog1.java";
        JavaCompiler jj = ToolProvider.getSystemJavaCompiler();
        int compile = jj.run(null, null, null, filetocompile);
        if (compile == 0) {
            System.out.println("comilation successfull");
        } else {
            System.out.println("compilation failed bro");
        }// TODO add your handling code here:
               Random rand = new Random();
        URL url;
        try {
            int tt = 0;
            url = new URL("file:///C:\\Users\\saksham\\Desktop\\");
            URLClassLoader ucl = new URLClassLoader(new URL[]{url});
            Class clazz = ucl.loadClass("prog1");
            Object o = clazz.newInstance();
            Method method = clazz.getMethod("hello", int.class);
            int m = 1,n=1;
            int j = 0;
            int time[] = new int[1000], size[] = new int[1000];
            for (int i = 100; i <=50000; i += 500) {
                tt = 0;
                int k = 2;
                m = 0;
                n=0;
                while (k > 0) {
                    //Scanner sc = new Scanner(new FileInputStream("C:\\Users\\saksham\\Desktop\\MINOR\\input" + m++ + ".txt"));
                    Scanner sc = new Scanner(new FileInputStream("C:\\Users\\saksham\\Desktop\\MINOR\\input0.txt"));
                    int p = 0, ar[] = new int[i];
                    while (p < i) {
                        ar[p] = sc.nextInt();
                        p++;
                    }
                    int temp1=ar[rand.nextInt(p)];
                    //System.setIn(new FileInputStream("C:\\Users\\saksham\\Desktop\\MINOR\\input" + n++ + ".txt"));
                    System.setIn(new FileInputStream("C:\\Users\\saksham\\Desktop\\MINOR\\input0.txt"));
                    long start_time = System.nanoTime();
                    method.invoke(o, i);
                    long end_time = System.nanoTime();
                    long time_elapsed = end_time - start_time;
                    time_elapsed /= 1000;
                    tt += time_elapsed;
                    k--;
                }
                tt /= 2;
                System.out.println("TIme Elapsed for size: " + i + " " + tt);
                time[j] = tt;
                size[j] = i;
                j++;
                //out_time.setText("TIME ELAPSED: \n"+time_elapsed/1000+"ms");
            }
            Minor_Project.data(time, size, j,"temp1");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  try {
            File f = new File("C:\\Users\\saksham\\desktop\\prog1.java");
            FileWriter fw = new FileWriter(f);
            PrintWriter pw = new PrintWriter(fw);
            String s;
            s = alg2.getText();
            System.out.println("String is: " + s);
            pw.print(s);
            fw.flush();

            fw.close();
        } catch (Exception e) {
        }   
    String filetocompile = "C:\\Users\\saksham\\desktop\\prog1.java";
        JavaCompiler jj = ToolProvider.getSystemJavaCompiler();
        int compile = jj.run(null, null, null, filetocompile);
        if (compile == 0) {
            System.out.println("comilation successfull");
        } else {
            System.out.println("compilation failed bro");
        }// TODO add your handling code here:
               Random rand = new Random();
        URL url;
        try {
            int tt = 0;
            url = new URL("file:///C:\\Users\\saksham\\Desktop\\");
            URLClassLoader ucl = new URLClassLoader(new URL[]{url});
            Class clazz = ucl.loadClass("prog1");
            Object o = clazz.newInstance();
            Method method = clazz.getMethod("hello", int.class);
            int m = 1,n=1;
            int j = 0;
            int time[] = new int[1000], size[] = new int[1000];
            for (int i = 100; i <= 50000; i += 500) {
                tt = 0;
                int k = 2;
                m = 0;
                n=0;
                while (k > 0) {
                    //Scanner sc = new Scanner(new FileInputStream("C:\\Users\\saksham\\Desktop\\MINOR\\input" + m++ + ".txt"));
                    Scanner sc = new Scanner(new FileInputStream("C:\\Users\\saksham\\Desktop\\MINOR\\input0.txt"));
                    int p = 0, ar[] = new int[i];
                    while (p < i) {
                        ar[p] = sc.nextInt();
                        p++;
                    }
                    int temp1=ar[rand.nextInt(p)];
                    //System.setIn(new FileInputStream("C:\\Users\\saksham\\Desktop\\MINOR\\input" + n++ + ".txt"));
                    System.setIn(new FileInputStream("C:\\Users\\saksham\\Desktop\\MINOR\\input0.txt"));
                    long start_time = System.nanoTime();
                    method.invoke(o, i);
                    long end_time = System.nanoTime();
                    long time_elapsed = end_time - start_time;
                    time_elapsed /= 1000;
                    tt += time_elapsed;
                    k--;
                }
                tt /= 2;
                System.out.println("TIme Elapsed for size: " + i + " " + tt);
                time[j] = tt;
                size[j] = i;
                j++;
                //out_time.setText("TIME ELAPSED: \n"+time_elapsed/1000+"ms");
            }
            Minor_Project.data(time, size, j,"temp2");
        } catch (Exception e) {
            e.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(comp_alg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(comp_alg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(comp_alg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(comp_alg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new comp_alg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alg1;
    private javax.swing.JTextArea alg2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
